### ISSUE TITLE
onAddItem doesn't work

### ISSUE THREAD

**Issue by AhmadAfshari** [Zicrael/ngx-tree-dnd#18]
**Describe the bug**
when onAddItem event triggers returns wrong parentList

**To Reproduce**
1. Go to https://stackblitz.com/edit/ngx-tree-dnd
2. make a console.log(event) in line 71.
3. Click on add new item button in front of Iphone item.
4. See console that shows the google play as parent not the apple item.

**Comment by Zicrael** [comment]
@AhmadAfshari thank you for find this strange bug!
I try fix this bug today.

**Comment by kapilpundit** [comment]
@Zicrael  Hi, has this issue been fixed?

**Comment by Zicrael** [comment]
@kapilpundit Hey man, almost i think i fix it today. Need time for this.

**Comment by kapilpundit** [comment]
Ok, no problem. Take your time. But not too much.

**Comment by Zicrael** [comment]
@kapilpundit , @AhmadAfshari this issue was fixed in 2.4.2 version. Please update package.
Thank you for report this issue!

**Comment by Zicrael** [comment]
https://stackblitz.com/edit/ngx-tree-dnd check again. All work fine. Thank you for report, i close the issue. In clsoe future i want improve this package to 3.0.0 version. With some new features.

**Comment by kapilpundit** [comment]
Thanks man, you saved the day. Really appreciate your effort.
