### ISSUE TITLE
How can I call an event when delete button is clicked?

### ISSUE THREAD

**Issue by kapilpundit** [Zicrael/ngx-tree-dnd#26]
Hi @Zicrael , This one is similar to an earlier issue I raised #16 . This time I would like you to provide two separate events when delete button is clicked.

Basically, I would like to ask for confirmation before a node is removed from the tree, so a (onStartDeleteItem) and (onFinishDeleteItem) events would be great!.

Thanks,

**Comment by Zicrael** [comment]
Hi @kapilpundit , okay this one not so hard, but any ideas about confirmation before remove child? modal or just alert or ...?

**Comment by Zicrael** [comment]
@kapilpundit  
FIXED in v2.5.0.
Now you can get submit on deleting items. There are 3 new events instead old one.
Example: 
```
  (onStartDeleteItem)='onStartDelete($event)'
  (onFinishDeleteItem)='onFinishDelete($event)'
  (onCancelDeleteItem)='onCancelDelete($event)'
```

**Comment by Zicrael** [comment]
You can check the live example in:
https://stackblitz.com/edit/ngx-tree-dnd
Hope you enjoy it. Thank you for the star.

**Comment by kapilpundit** [comment]
Nice work @Zicrael . Is there a way I can open my own modal div or a popup instead of the confirmation alert box? That would be great as I would like to show some informative message to the user for taking there consent to delete a node in the tree. Thanks.

**Comment by sarahm7** [comment]
i would like to know as well if we can override the alert message here. thanks!

**Comment by hirenkukadiya** [comment]
@sarahm7 you can override message from the script file. find msg and replace it in file.

**Comment by sarahm7** [comment]
sorry what do you mean @hirenkukadiya ? i meant the same as @kapilpundit sorry for the confusion.

**Comment by hirenkukadiya** [comment]
@sarahm7 just find "Do you really want to delete" in script and replace it.

**Comment by kumarant** [comment]
Hi @hirenkukadiya  @Zicrael 
is there a way to disable the confirmation alert dialog box on delete
