### ISSUE TITLE
How to hide root actions buttons.?

### ISSUE THREAD

**Issue by t2pdev01** [Zicrael/ngx-tree-dnd#31]
Can i hide main root or root actions button.?

**Comment by Zicrael** [comment]
Hello @t2pdev01 ,
Let me check, I will fix this issue today, and publish next version.

**Comment by Zicrael** [comment]
Hey @t2pdev01 ,  this feature already implemented. If you want hide action buttons, just make showActionButtons: false inside you config.

**Comment by hirenkukadiya** [comment]
Thanks,
But hide main root action button or i want only child records there are by default main root like in your example **Company Tree** but i want start with direct **Apple**, not from company tree so how to do it?

**Comment by Zicrael** [comment]
@hirenkukadiya  Ah i see, let me add ```showRootActionButtons``` option, and you can change it to false.

**Comment by Zicrael** [comment]
@hirenkukadiya , @t2pdev01 FIXED in v2.5.0. 
Now you can set ```showRootActionButtons: false``` in ```[config]```.

**Comment by Zicrael** [comment]
I close this issue, please check example: 
https://stackblitz.com/edit/ngx-tree-dnd
Hope you like it. Thank you for the star.
