### ISSUE TITLE
Unable load SVG in production build

### ISSUE THREAD

**Issue by Cbhavesh006** [Zicrael/ngx-tree-dnd#46]
**Describe the bug**
SVG icon unable to load in production mode in angular

**To Reproduce**
1. Make demo from https://stackblitz.com/edit/ngx-tree-dnd
2. ng build --prod to make build production
3. run application on browser(any) 
4. there are not able to see plus,minus,delete button in tree view

**Expected behavior**
when i see in production build there are missing icon of font-awesome which are useful to manage child and parent of tree.
in console showing to many errors for each icons like :
 FontAwesome: Could not find icon with iconName=plus and prefix=fas

**Screenshots**
![Screenshot from 2019-04-12 11-32-34](https://user-images.githubusercontent.com/49547108/56015450-b8a51100-5d16-11e9-83e8-4843f4abdb3b.png)
![Screenshot from 2019-04-12 11-33-32](https://user-images.githubusercontent.com/49547108/56015504-e12d0b00-5d16-11e9-9862-1556b4a95596.png)

**Comment by Zicrael** [comment]
Hello @Cbhavesh006 , sorry for late answer, looks strange.. let me check it.

**Comment by Cbhavesh006** [comment]
Solved issue by ref https://github.com/FortAwesome/angular-fontawesome
`import { faEdit,faMinus,faPlus,faTimes } from '@fortawesome/free-solid-svg-icons';`

**Comment by vr-virus** [comment]
Hello @Cbhavesh006, could you please share the step to resolve this issue. I have used your ref url but unable to resolve this issue.

**Comment by kalyaniSarode22** [comment]
I am facing the same issue..Can u please provide me steps to resolve that
